# Generated by Django 5.2.5 on 2025-10-12 07:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999)])),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='jobseekerprofile',
            old_name='education',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='expected_salary',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='experience',
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='skills',
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999)])),
                ('degree', models.CharField(max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('period', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='accounts.jobseekerprofile')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999)])),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('period', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='accounts.jobseekerprofile')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='jobseekers', to='accounts.skill'),
        ),
    ]
