# Generated by Django 5.2.5 on 2025-10-12 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_skill_rename_education_jobseekerprofile_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekerprofile',
            old_name='preferred_location',
            new_name='location',
        ),
    ]
