# Generated by Django 5.2.5 on 2025-10-12 10:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_preferred_location_jobseekerprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='employers', to='accounts.skill'),
        ),
        migrations.CreateModel(
            name='EmployerEducation',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999)])),
                ('degree', models.CharField(max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('period', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='accounts.employerprofile')),
            ],
            options={
                'verbose_name': 'Employer Education',
                'verbose_name_plural': 'Employer Educations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployerExperience',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999)])),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('period', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='accounts.employerprofile')),
            ],
            options={
                'verbose_name': 'Employer Experience',
                'verbose_name_plural': 'Employer Experiences',
                'ordering': ['-created_at'],
            },
        ),
    ]
